//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace UniversityOfMe.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class AutomatedEmailEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new AutomatedEmailEntities object using the connection string found in the 'AutomatedEmailEntities' section of the application configuration file.
        /// </summary>
        public AutomatedEmailEntities() : base("name=AutomatedEmailEntities", "AutomatedEmailEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new AutomatedEmailEntities object.
        /// </summary>
        public AutomatedEmailEntities(string connectionString) : base(connectionString, "AutomatedEmailEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new AutomatedEmailEntities object.
        /// </summary>
        public AutomatedEmailEntities(EntityConnection connection) : base(connection, "AutomatedEmailEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<EmailJob> EmailJobs
        {
            get
            {
                if ((_EmailJobs == null))
                {
                    _EmailJobs = base.CreateObjectSet<EmailJob>("EmailJobs");
                }
                return _EmailJobs;
            }
        }
        private ObjectSet<EmailJob> _EmailJobs;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the EmailJobs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToEmailJobs(EmailJob emailJob)
        {
            base.AddObject("EmailJobs", emailJob);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AutomatedEmailModel", Name="EmailJob")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class EmailJob : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new EmailJob object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="fromEmail">Initial value of the FromEmail property.</param>
        /// <param name="toEmail">Initial value of the ToEmail property.</param>
        /// <param name="subject">Initial value of the Subject property.</param>
        /// <param name="body">Initial value of the Body property.</param>
        /// <param name="dateTimeStamp">Initial value of the DateTimeStamp property.</param>
        /// <param name="presentSent">Initial value of the PresentSent property.</param>
        /// <param name="postsentSent">Initial value of the PostsentSent property.</param>
        public static EmailJob CreateEmailJob(global::System.Int32 id, global::System.String fromEmail, global::System.String toEmail, global::System.String subject, global::System.String body, global::System.DateTime dateTimeStamp, global::System.Boolean presentSent, global::System.Boolean postsentSent)
        {
            EmailJob emailJob = new EmailJob();
            emailJob.Id = id;
            emailJob.FromEmail = fromEmail;
            emailJob.ToEmail = toEmail;
            emailJob.Subject = subject;
            emailJob.Body = body;
            emailJob.DateTimeStamp = dateTimeStamp;
            emailJob.PresentSent = presentSent;
            emailJob.PostsentSent = postsentSent;
            return emailJob;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FromEmail
        {
            get
            {
                return _FromEmail;
            }
            set
            {
                OnFromEmailChanging(value);
                ReportPropertyChanging("FromEmail");
                _FromEmail = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FromEmail");
                OnFromEmailChanged();
            }
        }
        private global::System.String _FromEmail;
        partial void OnFromEmailChanging(global::System.String value);
        partial void OnFromEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ToEmail
        {
            get
            {
                return _ToEmail;
            }
            set
            {
                OnToEmailChanging(value);
                ReportPropertyChanging("ToEmail");
                _ToEmail = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ToEmail");
                OnToEmailChanged();
            }
        }
        private global::System.String _ToEmail;
        partial void OnToEmailChanging(global::System.String value);
        partial void OnToEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Subject
        {
            get
            {
                return _Subject;
            }
            set
            {
                OnSubjectChanging(value);
                ReportPropertyChanging("Subject");
                _Subject = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Subject");
                OnSubjectChanged();
            }
        }
        private global::System.String _Subject;
        partial void OnSubjectChanging(global::System.String value);
        partial void OnSubjectChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Body
        {
            get
            {
                return _Body;
            }
            set
            {
                OnBodyChanging(value);
                ReportPropertyChanging("Body");
                _Body = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Body");
                OnBodyChanged();
            }
        }
        private global::System.String _Body;
        partial void OnBodyChanging(global::System.String value);
        partial void OnBodyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateTimeStamp
        {
            get
            {
                return _DateTimeStamp;
            }
            set
            {
                OnDateTimeStampChanging(value);
                ReportPropertyChanging("DateTimeStamp");
                _DateTimeStamp = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateTimeStamp");
                OnDateTimeStampChanged();
            }
        }
        private global::System.DateTime _DateTimeStamp;
        partial void OnDateTimeStampChanging(global::System.DateTime value);
        partial void OnDateTimeStampChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean PresentSent
        {
            get
            {
                return _PresentSent;
            }
            set
            {
                OnPresentSentChanging(value);
                ReportPropertyChanging("PresentSent");
                _PresentSent = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PresentSent");
                OnPresentSentChanged();
            }
        }
        private global::System.Boolean _PresentSent;
        partial void OnPresentSentChanging(global::System.Boolean value);
        partial void OnPresentSentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean PostsentSent
        {
            get
            {
                return _PostsentSent;
            }
            set
            {
                OnPostsentSentChanging(value);
                ReportPropertyChanging("PostsentSent");
                _PostsentSent = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PostsentSent");
                OnPostsentSentChanged();
            }
        }
        private global::System.Boolean _PostsentSent;
        partial void OnPostsentSentChanging(global::System.Boolean value);
        partial void OnPostsentSentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DateTimeStampSent
        {
            get
            {
                return _DateTimeStampSent;
            }
            set
            {
                OnDateTimeStampSentChanging(value);
                ReportPropertyChanging("DateTimeStampSent");
                _DateTimeStampSent = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateTimeStampSent");
                OnDateTimeStampSentChanged();
            }
        }
        private Nullable<global::System.DateTime> _DateTimeStampSent;
        partial void OnDateTimeStampSentChanging(Nullable<global::System.DateTime> value);
        partial void OnDateTimeStampSentChanged();

        #endregion
    
    }

    #endregion
    
}
