<%@ Page Title="" Language="C#" MasterPageFile="~/Views/Shared/Site.Master" Inherits="System.Web.Mvc.ViewPage<dynamic>" %>

<asp:Content ID="Content1" ContentPlaceHolderID="TitleContent" runat="server">
	Privacy Policy
</asp:Content>

<asp:Content ID="Content2" ContentPlaceHolderID="MainContent" runat="server">
	<div class="push-2 col-20">
		<div class="col-20 spacer-30">&nbsp;</div>
		<div class="clear">&nbsp;</div>
		
    	<div class="push-1 col-4 center p-t5 p-b5 t-tab b-wht">
    		<span class="fnt-16 tint-6 bold">Privacy Policy</span>
    	</div>
    	<div class="clear">&nbsp;</div>
    	
    	<div class="b-wht">
    		<div class="push-1 col-18 fnt-14">
    			<div class="spacer-30">&nbsp;</div>
    			<div class="clear">&nbsp;</div>
	
				<h4 class="fnt-14">What personal information we store</h4>
				Once a user registers an account with Have a Voice, all of the information entered is stored in a secure database.
				This information includes first name, last name, email, date of birth, and gender.
				Personal information is only used for display purposes and authentication.
				Personal information can be changed at any time.
				<br /><br />
				<h4 class="fnt-14">Passwords</h4>
				Passwords are not stored in plaintext, but instead they are hashed to an unreadable string before being stored.
				Passwords can be changed at any time.
				<br /><br />
				<h4 class="fnt-14">Email</h4>
				An email address is how we verify an account.
				We will never disclose your email to anyone.
				Communication between users can be done within the system between profile comments and the private messaging system.
				The only emails we will send to users include: account confirmation and forgot password requests.
				<br /><br />
				<h4 class="fnt-14">Privacy settings</h4>
				Every new account is created with a default set of privacy settings.
				These privacy settings define how the user’s account behaves in relation to other accounts.
				These settings can be changed at any time.
				<br /><br />
				<h4 class="fnt-14">Sharing of data</h4>
				Have a Voice will not share your personal data and site activity with third parties.
				<br /><br />
				<h4 class="fnt-14">Cookies</h4>
				Cookies are only used when a user logs in and specifies the <i>remember me</i> option.
				A cookie is then stored on the local computer that will identify the user once returned.
				The only information stored in the cookie is a unique personal identification number that is automatically generated by the system to identify the user 
                and an automatically generated hash code that will verify that the cookie is associated with that personal 
                identification number.
				<br /><br />
				<h4 class="fnt-14">Privacy Policy Changes</h4>
				Have a Voice may change its Privacy Policy from time to time, and in Have a Voice’s sole discretion.
				Have a Voice encourages visitors to frequently check this page for any changes to its Privacy Policy.
				<br /><br />
				<h4 class="fnt-14">Questions and Concerns</h4>
				If a visitor has any questions or concerns about this policy or their privacy on Have a Voice, 
                please go to the <a href="/Site/ContactUs" class="sitelink">Contact Us</a> page and select <b>Privacy</b> from the <b>Inquiry Type</b> menu.
                <br /><br /><br /><br />
				<div class="clear">&nbsp;</div>
			</div>
			<div class="clear">&nbsp;</div>
		</div>
		<div class="clear">&nbsp;</div>
	</div>
</asp:Content>
