<%@ Page Title="" Language="C#" MasterPageFile="~/Views/Shared/Site.Master" Inherits="System.Web.Mvc.ViewPage<dynamic>" %>

<asp:Content ID="Content1" ContentPlaceHolderID="TitleContent" runat="server">
	Result
</asp:Content>

<asp:Content ID="Content2" ContentPlaceHolderID="MainContent" runat="server">

    <div class="normal-page">
        <div class="padding-col">
            <div class="heading">Privacy Settings</div>
            <div class="sub-heading">What personal information we store</div>
            Once a user registers an account with Have a Voice, all of the information entered is stored in a secure database. This information includes first name, last name, email, date of birth, and gender. Personal information is only used for display purposes and authentication. Personal information can be changed at any time.
            <br /><br />
            <div class="sub-heading">Passwords</div>
            Passwords are not stored in plaintext, but instead they are hashed to an unreadable string before being stored. Passwords can be changed at any time.
            <br /><br />
            <div class="sub-heading">Email</div>
            An email address is how we verify an account. We will never disclose your email to anyone. Communication between users can be done within the system between profile comments and the private messaging system. The only emails we will send to users include: account confirmation and forgot password requests.
            <br /><br />
            <div class="sub-heading">Privacy settings</div>
            Every new account is created with a default set of privacy settings. These privacy settings define how the user’s account behaves in relation to other accounts. These settings can be changed at any time.
            <br /><br />
            <div class="sub-heading">Sharing of data</div>
            Have a Voice will not share your personal data and site activity with third parties.
            <br /><br />
            <div class="sub-heading">Cookies</div>
            Cookies are only used when a user logs in and specifies the remember me option. A cookie is then stored on the local computer that will identify the user once returned. The only information stored in the cookie is a unique personal identification number that is automatically generated by the system to identify the user and an automatically generated hash code that will verify that the cookie is associated with that personal identification number.
            <br /><br />
            <div class="sub-heading">Privacy Policy Changes</div>
            Have a Voice may change its Privacy Policy from time to time, and in Have a Voice’s sole discretion. Have a Voice encourages visitors to frequently check this page for any changes to its Privacy Policy.
            <br /><br />
            <div class="sub-heading">Questions and Concerns</div>
            If a visitor has any questions or concerns about this policy or their privacy on Have a Voice, please go to the Contact Us page and select Privacy from the Inquiry Type menu. 
        </div>
    </div>

</asp:Content>

